#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from geometry_msgs.msg import PoseStamped
from datetime import datetime

remote_franka_pose = PoseStamped()

def teleman_talker():
    global remote_franka_pose
    rospy.init_node('test_publisher', anonymous=True)
    pub = rospy.Publisher('/teleop_franka', PoseStamped, queue_size=10)
    rate = rospy.Rate(10) # 10hz

    while not rospy.is_shutdown():
        if remote_franka_pose.pose.position.x < 0.8:
            remote_franka_pose.pose.position.x += 0.002 #front/back

            if remote_franka_pose.pose.position.x > 0.8:
                print("test publisher ends at")
                print(datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])

        #remote_franka_pose.pose.position.y += 0.04 #left/right
        #remote_franka_pose.pose.position.z += 0.04 #up/down

        #haptic_pose.pose.position.x = 5.0 #front/back
        #haptic_pose.pose.position.y = -0.1 #left/right
        #haptic_pose.pose.position.z = 6.0 #up/down

        #remote_franka_pose.pose.orientation.x = 0.7071068
        #remote_franka_pose.pose.orientation.y = 0.000
        #remote_franka_pose.pose.orientation.z = 0.7071068
        #remote_franka_pose.pose.orientation.w = 0.000

        pub.publish(remote_franka_pose)
        rate.sleep()




if __name__ == '__main__':
    print("test publisher starts at")
    print(datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])



    #get current robot position
    #haptic_pose.header.frame_id = "s1"

    #haptic_pose.pose.position.x = 5.0  # front/back
    #haptic_pose.pose.position.y = 0.0  # left/right
    #haptic_pose.pose.position.z = 6.0  # up/down

    #haptic_pose.pose.orientation.x = 0.7071068
    #haptic_pose.pose.orientation.y = 0.000
    #haptic_pose.pose.orientation.z = 0.7071068
    #haptic_pose.pose.orientation.w = 0.000


    remote_franka_pose.pose.position.x = 0.57
    remote_franka_pose.pose.position.y = 0.32
    remote_franka_pose.pose.position.z = 0.58 + 0.9

    remote_franka_pose.pose.orientation.x = 0.1830127
    remote_franka_pose.pose.orientation.y = 0.6830127
    remote_franka_pose.pose.orientation.z = 0.1830127
    remote_franka_pose.pose.orientation.w = 0.6830127


    try:
        teleman_talker()
    except rospy.ROSInterruptException:
        pass
